//theme_import()
function theme_import(){
	var _loc = game_save_id + "\\Theme\\"
	//Import images
	sprite_replace(spr_wallpaper,_loc + "wallpaper.png",0,0,0,0,0)
	sprite_replace(spr_topbar,_loc + "topbar.png",0,0,0,0,0)
	sprite_replace(spr_logo,_loc + "logo.png",0,0,0,sprite_get_width(spr_logo) / 2,sprite_get_height(spr_logo) / 2)
	sprite_replace(spr_addgame,_loc + "addgame_button.png",0,0,0,0,0)
	sprite_replace(spr_allapps,_loc + "allapps_button.png",0,0,0,0,0)
	sprite_replace(spr_news,_loc + "news_button.png",0,0,0,0,0)
	sprite_replace(spr_settings,_loc + "settings_button.png",0,0,0,0,0)
	sprite_replace(spr_shop,_loc + "shop_button.png",0,0,0,0,0)
	sprite_replace(spr_addgameicon,_loc + "addgame_icon.png",0,0,0,0,0)
	sprite_replace(spr_allappsicon,_loc + "allapps_icon.png",0,0,0,0,0)
	sprite_replace(spr_newsicon,_loc + "news_icon.png",0,0,0,0,0)
	sprite_replace(spr_settingsicon,_loc + "settings_icon.png",0,0,0,0,0)
	sprite_replace(spr_profileicon,_loc + "profile_icon.png",0,0,0,0,0)
	sprite_replace(spr_clock,_loc + "clock.png",0,0,0,sprite_get_width(spr_clock) / 2,sprite_get_height(spr_clock) / 2)
	sprite_replace(spr_updateicon,_loc + "update_0.png",0,0,0,sprite_get_width(spr_updateicon) / 2,sprite_get_height(spr_updateicon) / 2)
	sprite_replace(spr_updateicon,_loc + "update_1.png",1,0,0,sprite_get_width(spr_updateicon) / 2,sprite_get_height(spr_updateicon) / 2)
	sprite_replace(spr_scroll_vertical,_loc + "scrollbar_vertical.png",0,0,0,0,0)
	sprite_replace(spr_nogameicon,_loc + "nogameicon.png",0,0,0,0,0)
	sprite_replace(spr_keyboard,_loc + "keyboard_dark.png",0,0,0,sprite_get_width(spr_keyboard) / 2,sprite_get_height(spr_keyboard) / 2)
	sprite_replace(spr_keyboard,_loc + "keyboard_light.png",1,0,0,sprite_get_width(spr_keyboard) / 2,sprite_get_height(spr_keyboard) / 2)
	sprite_replace(spr_cursor_custom,_loc + "cursor.png",0,0,0,0,0)
	//Import settings
	ini_open(_loc + "settings.ini")
	global.Col_Highlight1 = ini_read_real("Highlight Color","Color 1",global.Col_Highlight1)
	global.Col_Highlight2 = ini_read_real("Highlight Color","Color 2",global.Col_Highlight2)
	global.Col_Update1 = ini_read_real("Update Color","Color 1",global.Col_Update1)
	global.Col_Update2 = ini_read_real("Update Color","Color 2",global.Col_Update2)
	global.Col_TopBarText = ini_read_real("Top Bar","Text Color",global.Col_TopBarText)
	global.TopIconsHighlight = ini_read_real("Top Bar","Highlight Buttons",global.TopIconsHighlight)
	global.TopIconsNames = ini_read_real("Top Bar","Button Names",global.TopIconsNames)
	ini_close()
}