//theme_import()
function theme_import(){
	var _loc = game_save_id + "\\Theme\\"
	//Import images
	sprite_replace(spr_wallpaper,_loc + "wallpaper.png",0,0,0,0,0)
	sprite_replace(spr_topbar,_loc + "topbar.png",0,0,0,0,0)
	sprite_replace(spr_logo,_loc + "logo.png",0,0,0,0,0)
	sprite_set_offset(spr_logo,sprite_get_width(spr_logo) / 2,sprite_get_height(spr_logo) / 2)
	sprite_replace(spr_addgame,_loc + "addgame_button.png",0,0,0,0,0)
	sprite_set_offset(spr_addgame,sprite_get_width(spr_addgame) / 2,sprite_get_height(spr_addgame) / 2)
	sprite_replace(spr_settings,_loc + "settings_button.png",0,0,0,0,0)
	sprite_set_offset(spr_settings,sprite_get_width(spr_settings) / 2,sprite_get_height(spr_settings) / 2)
	sprite_replace(spr_shop,_loc + "shop_button.png",0,0,0,0,0)
	sprite_set_offset(spr_shop,sprite_get_width(spr_shop) / 2,sprite_get_height(spr_shop) / 2)
	sprite_replace(spr_allapps,_loc + "allapps_button.png",0,0,0,0,0)
	sprite_set_offset(spr_allapps,sprite_get_width(spr_allapps) / 2,sprite_get_height(spr_allapps) / 2)
	sprite_replace(spr_news,_loc + "news_button.png",0,0,0,0,0)
	sprite_set_offset(spr_news,sprite_get_width(spr_news) / 2,sprite_get_height(spr_news) / 2)
	sprite_replace(spr_addgameicon,_loc + "addgame_icon.png",0,0,0,0,0)
	sprite_replace(spr_allappsicon,_loc + "allapps_icon.png",0,0,0,0,0)
	sprite_replace(spr_newsicon,_loc + "news_icon.png",0,0,0,0,0)
	sprite_replace(spr_settingsicon,_loc + "settings_icon.png",0,0,0,0,0)
	sprite_replace(spr_profileicon,_loc + "profile_icon.png",0,0,0,0,0)
	sprite_replace(spr_clock,_loc + "clock.png",0,0,0,0,0)
	sprite_set_offset(spr_clock,sprite_get_width(spr_clock) / 2,sprite_get_height(spr_clock) / 2)
	sprite_replace(spr_updateicon,_loc + "update_0.png",0,0,0,0,0)
	sprite_replace(spr_updateicon,_loc + "update_1.png",1,0,0,0,0)
	sprite_set_offset(spr_updateicon,sprite_get_width(spr_updateicon) / 2,sprite_get_height(spr_updateicon) / 2)
	sprite_replace(spr_scroll_vertical,_loc + "scrollbar_vertical.png",0,0,0,0,0)
	sprite_replace(spr_nogameicon,_loc + "nogameicon.png",0,0,0,0,0)
	sprite_replace(spr_keyboard,_loc + "keyboard_dark.png",0,0,0,0,0)
	sprite_replace(spr_keyboard,_loc + "keyboard_light.png",1,0,0,0,0)
	sprite_set_offset(spr_keyboard,sprite_get_width(spr_keyboard) / 2,sprite_get_height(spr_keyboard) / 2)
	sprite_replace(spr_cursor_custom,_loc + "cursor.png",0,0,0,0,0)
	//Import settings
	ini_open(_loc + "settings.ini")
	global.Col_Highlight1 = ini_read_real("Highlight Color","Color 1",global.Col_Highlight1)
	global.Col_Highlight2 = ini_read_real("Highlight Color","Color 2",global.Col_Highlight2)
	global.Col_Update1 = ini_read_real("Update Color","Color 1",global.Col_Update1)
	global.Col_Update2 = ini_read_real("Update Color","Color 2",global.Col_Update2)
	global.Col_TopBarText = ini_read_real("Top Bar","Text Color",global.Col_TopBarText)
	global.TopIconsHighlight = ini_read_real("Top Bar","Highlight Buttons",global.TopIconsHighlight)
	global.TopIconsNames = ini_read_real("Top Bar","Button Names",global.TopIconsNames)
	global.TopBtn_Addgame_x = ini_read_real("Top Bar","Addgame Button X",global.TopBtn_Addgame_x)
	global.TopBtn_Addgame_y = ini_read_real("Top Bar","Addgame Button Y",global.TopBtn_Addgame_y)
	global.TopBtn_Settings_x = ini_read_real("Top Bar","Settings Button X",global.TopBtn_Settings_x)
	global.TopBtn_Settings_y = ini_read_real("Top Bar","Settings Button Y",global.TopBtn_Settings_y)
	global.TopBtn_Shop_x = ini_read_real("Top Bar","Shop Button X",global.TopBtn_Shop_x)
	global.TopBtn_Shop_y = ini_read_real("Top Bar","Shop Button Y",global.TopBtn_Shop_y)
	global.TopBtn_Apps_x = ini_read_real("Top Bar","Apps Button X",global.TopBtn_Apps_x)
	global.TopBtn_Apps_y = ini_read_real("Top Bar","Apps Button Y",global.TopBtn_Apps_y)
	global.TopBtn_News_x = ini_read_real("Top Bar","News Button X",global.TopBtn_News_x)
	global.TopBtn_News_y = ini_read_real("Top Bar","News Button Y",global.TopBtn_News_y)
	global.Profile_x = ini_read_real("Top Bar","Profile X",global.Profile_x)
	global.Profile_y = ini_read_real("Top Bar","Profile Y",global.Profile_y)
	global.Updateicon_x = ini_read_real("Top Bar","Update Icon X",global.Updateicon_x)
	global.Updateicon_y = ini_read_real("Top Bar","Update Icon Y",global.Updateicon_y)
	global.Clock_x = ini_read_real("Top Bar","Clock X",global.Clock_x)
	global.Clock_y = ini_read_real("Top Bar","Clock Y",global.Clock_y)
	ini_close()
}